<a href="https://colab.research.google.com/github/Mr-MaNia7/deep-learning/blob/main/Deep_learning_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



**Done by: ABDULKARIM GETACHEW MOHAMMED  - UGR/7992/12**



Coding Neural Networks Part 1

In [94]:
import torch

In [95]:
# Give manual seed
torch.manual_seed(7)

In [96]:
# Create four random inputs and weights
random_input = torch.rand(4)
random_weights = torch.rand(4)
bias = 1

print("input: ", random_input)
print("weights: ", random_weights)
print("bias: ", bias)

input:  tensor([0.5349, 0.1988, 0.6592, 0.6569])
weights:  tensor([0.2328, 0.4251, 0.2071, 0.6297])
bias:  1


In [97]:
# Neural Networks
output = torch.matmul(random_input, random_weights) + bias
output

tensor(1.7592)

Layer of Neurons

In [98]:
random_input2 = torch.rand(4)
random_weight2 = torch.rand(size=(5, 4))
bias = torch.rand(5)

random_weight2, random_input2, bias

(tensor([[0.2868, 0.2063, 0.4451, 0.3593],
         [0.7204, 0.0731, 0.9699, 0.1078],
         [0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286],
         [0.7653, 0.1132, 0.8559, 0.6721]]),
 tensor([0.3653, 0.8513, 0.8549, 0.5509]),
 tensor([0.6267, 0.5691, 0.7437, 0.9592, 0.3887]))

In [99]:
output2 = torch.matmul(random_input2, random_weight2.T) + bias

output2

tensor([1.4855, 1.7830, 2.4482, 2.7529, 1.8667])

In [100]:
input2 = output2
output_weight = torch.rand(size = (2, 5))
bias2 = torch.rand(2)

input2, output_weight, bias2

(tensor([1.4855, 1.7830, 2.4482, 2.7529, 1.8667]),
 tensor([[0.2214, 0.3742, 0.1953, 0.7405, 0.2529],
         [0.2332, 0.9314, 0.9575, 0.5575, 0.4134]]),
 tensor([0.4355, 0.7369]))

In [101]:
final_output = torch.matmul(input2, output_weight.T) + bias2

final_output

tensor([4.4203, 7.3947])

Layer of Neurons & Batch of Data

In [102]:
inputs = torch.rand((32, 4))
weights = torch.rand((5, 4))
bias = torch.rand(5)

In [103]:
outputs = torch.matmul(inputs, weights.T) + bias
outputs

tensor([[1.6543, 1.6943, 1.5751, 2.6870, 2.1138],
        [1.0972, 1.4359, 0.8589, 1.9007, 1.4669],
        [1.8271, 1.9258, 1.2835, 2.8056, 2.0718],
        [1.4980, 1.4699, 0.7123, 2.0361, 1.6514],
        [1.5119, 1.5245, 1.0336, 2.1780, 1.6974],
        [1.9718, 1.8789, 1.2904, 2.7172, 1.9634],
        [1.6226, 1.8240, 1.4351, 2.7307, 2.0601],
        [2.1393, 1.8912, 1.4019, 2.8984, 2.1945],
        [1.1148, 1.2406, 0.7004, 1.7779, 1.5907],
        [1.9136, 1.9426, 1.3587, 2.9119, 2.1917],
        [1.6891, 1.7394, 1.1649, 2.3799, 1.6654],
        [0.8861, 1.1474, 0.5075, 1.4251, 1.2173],
        [1.7536, 2.1516, 1.3089, 2.9117, 1.9329],
        [1.0657, 1.2456, 0.8334, 1.8166, 1.6081],
        [1.4522, 1.4249, 0.6962, 2.0834, 1.8102],
        [1.8329, 2.0571, 1.5266, 2.9293, 2.0065],
        [1.3675, 1.3999, 0.6250, 1.9037, 1.5733],
        [1.4141, 1.5330, 1.1248, 2.2499, 1.7892],
        [1.8015, 1.5617, 0.9505, 2.3870, 1.9965],
        [1.3228, 1.3018, 0.8900, 1.8791, 1.5787],


Adding Layers

In [104]:
inputs_1 = torch.rand((32, 4))
weights_1 = torch.rand((5, 4))
bias_1 = torch.rand(5)

In [105]:
outputs_1 = torch.matmul(inputs_1, weights_1.T) + bias_1

In [106]:
inputs_layer_2 = outputs_1
weights_layer_2 = torch.rand(5, 5)
bias_2 = torch.rand(5)

In [107]:
outputs_layer_2 = torch.matmul(inputs_layer_2, weights_layer_2.T) + bias_2

In [108]:
inputs_final_layer = outputs_layer_2
weights_final_layer = torch.rand(3, 5)
bias_3 = torch.rand(3)

In [109]:
final_output = torch.matmul(inputs_final_layer, weights_final_layer.T) + bias_3

In [110]:
final_output

tensor([[11.5630,  7.3813,  9.2195],
        [18.7143, 11.7044, 14.6889],
        [18.1017, 11.3229, 14.2526],
        [19.1926, 11.9970, 15.0331],
        [16.3504, 10.2651, 12.8674],
        [12.7509,  8.0237, 10.0779],
        [12.6005,  7.9399, 10.0333],
        [17.7438, 11.1298, 13.8983],
        [20.5305, 12.7193, 16.0941],
        [16.4030, 10.2678, 12.9440],
        [14.0950,  8.9891, 11.1230],
        [14.5953,  9.3086, 11.5115],
        [18.8056, 11.7744, 14.7856],
        [16.5258, 10.3404, 12.9805],
        [15.5240,  9.8208, 12.2437],
        [14.8575,  9.4360, 11.6806],
        [16.0034, 10.1232, 12.6533],
        [14.4933,  9.1646, 11.4349],
        [ 9.4760,  6.0881,  7.5842],
        [22.7074, 14.0822, 17.7667],
        [12.4005,  7.8338,  9.8633],
        [10.7669,  6.9278,  8.5071],
        [13.3949,  8.4515, 10.6374],
        [20.4715, 12.7093, 16.0862],
        [17.8318, 11.0979, 13.9651],
        [14.8192,  9.2114, 11.7148],
        [10.3861,  6.6448,  8.2685],
 

Coding Neural Networks with Object Oriented Programming/OOP

In [111]:
class DenseLayer:
  """Class for creating hidden layers."""
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weight = 0.01 * torch.rand((n_inputs, n_neurons))
    self.bias = torch.zeros(1, n_neurons)

  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weight) + self.bias


In [112]:
x = torch.rand((2, 4))

layer1 = DenseLayer(4, 6)
layer2 = DenseLayer(6, 5)
output_layer = DenseLayer(5, 2)

In [113]:
layer1.forward(x)
layer2.forward(layer1.output)
output_layer.forward(layer2.output)

In [114]:
output_layer.output

tensor([[9.2962e-06, 7.4955e-06],
        [1.0698e-05, 8.7042e-06]])

In [115]:
# Home Assignment
# 5 inputs
# 3 hidden layers: 16 layer, 16 layer, 16 layer
# 5 classes

In [116]:
input_layer = torch.rand((20, 5))
layer_1 = DenseLayer(5, 16)
layer_2 = DenseLayer(16, 16)
layer_3 = DenseLayer(16, 16)
output_layer = DenseLayer(16, 5)

In [117]:
layer_1.forward(input_layer)
layer_2.forward(layer_1.output)
layer_3.forward(layer_2.output)
output_layer.forward(layer_3.output)

In [118]:
output_layer.output

tensor([[9.9536e-06, 7.5420e-06, 7.1793e-06, 8.5245e-06, 7.7175e-06],
        [8.9618e-06, 6.7915e-06, 6.4614e-06, 7.6722e-06, 6.9487e-06],
        [8.0709e-06, 6.1132e-06, 5.8214e-06, 6.9161e-06, 6.2538e-06],
        [8.1396e-06, 6.1654e-06, 5.8709e-06, 6.9737e-06, 6.3087e-06],
        [8.6427e-06, 6.5506e-06, 6.2351e-06, 7.3992e-06, 6.7040e-06],
        [6.6828e-06, 5.0673e-06, 4.8186e-06, 5.7220e-06, 5.1754e-06],
        [8.8205e-06, 6.6815e-06, 6.3611e-06, 7.5547e-06, 6.8401e-06],
        [9.5297e-06, 7.2257e-06, 6.8692e-06, 8.1547e-06, 7.3864e-06],
        [5.2900e-06, 4.0093e-06, 3.8125e-06, 4.5259e-06, 4.1025e-06],
        [8.8286e-06, 6.6907e-06, 6.3696e-06, 7.5640e-06, 6.8403e-06],
        [1.1732e-05, 8.8935e-06, 8.4606e-06, 1.0046e-05, 9.0895e-06],
        [8.9283e-06, 6.7690e-06, 6.4423e-06, 7.6455e-06, 6.9219e-06],
        [9.5627e-06, 7.2477e-06, 6.8961e-06, 8.1876e-06, 7.4107e-06],
        [7.5229e-06, 5.7045e-06, 5.4246e-06, 6.4416e-06, 5.8236e-06],
        [1.1388e-05,